export type OpportunityLevel = "oro" | "plata" | "bronce";

export type BusinessOpportunity = {
  id: string;
  level: OpportunityLevel;
  priority: boolean;
  title: string;
  potential: string;
  cost: string;
  time: string;
  summary: string;
  actions: string[];
  examples: string[];
};

export const OPPORTUNITY_LEVELS: Record<OpportunityLevel, { title: string; detail: string }> = {
  oro: { title: "Oro", detail: "Implementar esta semana. Impacto directo en ingresos." },
  plata: { title: "Plata", detail: "Implementar este mes. Diferencia el sistema." },
  bronce: { title: "Bronce", detail: "Expansion futura cuando el sistema este rodando." },
};

export const BUSINESS_OPPORTUNITIES: BusinessOpportunity[] = [
  {
    id: "ai-tools-affiliates",
    level: "oro",
    priority: true,
    title: "Afiliados de herramientas IA",
    potential: "$500-$2.000/mes recurrente",
    cost: "$0",
    time: "1 semana",
    summary: "Programas de IA con comisiones recurrentes mensuales mientras el cliente siga suscrito.",
    actions: ["Registrarse en programas de IA", "Crear categoria Herramientas IA", "Publicar productos digitales con enlaces aprobados"],
    examples: ["Copy.ai 45%", "GetResponse 33%", "Synthesia 25%", "Writesonic 30%", "Jasper AI 25%", "QuillBot 20%"],
  },
  {
    id: "financial-affiliates",
    level: "oro",
    priority: false,
    title: "Afiliados de programas financieros",
    potential: "$200-$2.000/mes por leads",
    cost: "$0",
    time: "1 semana",
    summary: "Programas B2B y financieros que pagan por lead, registro o cuenta activa.",
    actions: ["Registrar cuentas en programas financieros", "Crear seccion Software de Negocios", "Publicar enlaces aprobados por proveedor"],
    examples: ["Factorial HR $200", "Holded $150", "Revolut Business $50-$100", "Wise $25", "Stripe variable"],
  },
  {
    id: "dynamic-pricing",
    level: "oro",
    priority: false,
    title: "Sistema de precios dinamicos",
    potential: "+30-50% CTR en tienda",
    cost: "$0",
    time: "4 horas",
    summary: "Detectar bajadas de precio y convertir productos en ofertas destacadas automaticamente.",
    actions: ["Comparar precio actual vs 24h", "Marcar badge OFERTA si baja mas de 10%", "Publicar alertas si baja mas de 20%"],
    examples: ["Badge OFERTA", "Seccion deals", "Telegram o redes para bajadas fuertes"],
  },
  {
    id: "weekly-newsletter",
    level: "oro",
    priority: true,
    title: "Newsletter semanal automatica con IA",
    potential: "$50-$500/semana adicionales",
    cost: "$0",
    time: "1 semana",
    summary: "Lista propia de email con las mejores ofertas semanales generadas por IA.",
    actions: ["Anadir formulario de suscripcion", "Enviar con Resend", "Generar email semanal con top ofertas"],
    examples: ["5 mejores ofertas", "Resumen semanal", "Productos destacados"],
  },
  {
    id: "multi-provider-comparison",
    level: "oro",
    priority: false,
    title: "Comparador multi-proveedor",
    potential: "+20-30% conversion",
    cost: "$0",
    time: "1 dia",
    summary: "Agrupar el mismo producto entre varios proveedores para mostrar mejor precio y comision.",
    actions: ["Detectar productos similares", "Guardar variantes por proveedor", "Mostrar comparador en ficha publica"],
    examples: ["Amazon vs eBay", "AliExpress vs Temu", "Mejor precio", "Mejor comision"],
  },
  {
    id: "multi-language-store",
    level: "plata",
    priority: false,
    title: "Tienda multi-idioma automatica",
    potential: "50% mas ingresos globales",
    cost: "$0",
    time: "2 semanas",
    summary: "Traducir tienda, SEO y fichas para vender en mercados con comisiones mas altas.",
    actions: ["Anadir internacionalizacion", "Traducir fichas con IA", "Crear rutas por idioma"],
    examples: ["EN", "PT", "FR", "Amazon USA"],
  },
  {
    id: "telegram-deals",
    level: "plata",
    priority: true,
    title: "Canal Telegram de ofertas",
    potential: "200-1.000 clics/dia",
    cost: "$0",
    time: "3 dias",
    summary: "Canal publico para publicar ofertas, bajadas de precio y productos top.",
    actions: ["Crear bot con BotFather", "Crear canal publico", "Publicar mejores ofertas automaticamente"],
    examples: ["3 posts diarios", "Ofertas flash", "Productos destacados"],
  },
  {
    id: "ai-video-reviews",
    level: "plata",
    priority: false,
    title: "Reviews en video con IA",
    potential: "2x-5x conversion",
    cost: "$0",
    time: "1 semana",
    summary: "Generar videos cortos de review para productos top y aumentar conversion.",
    actions: ["Seleccionar productos top", "Generar guion IA", "Crear video desde texto o flujo local"],
    examples: ["Pictory", "ComfyUI", "Shorts", "Reels"],
  },
  {
    id: "personalized-recommendations",
    level: "plata",
    priority: false,
    title: "Recomendacion personalizada",
    potential: "+20-30% ventas/sesion",
    cost: "$0",
    time: "1 semana",
    summary: "Recomendar productos por historial de vistas y productos vistos juntos.",
    actions: ["Guardar vistas anonimas", "Calcular productos relacionados", "Mostrar recomendaciones por sesion"],
    examples: ["Tambien visto", "Comprados juntos", "Recomendado para ti"],
  },
  {
    id: "cashback-system",
    level: "plata",
    priority: false,
    title: "Sistema de cashback",
    potential: "Fidelizacion 3x",
    cost: "5% comision",
    time: "3 dias",
    summary: "Devolver una parte pequena de la comision para aumentar retorno y confianza.",
    actions: ["Generar credito tras conversion", "Enviar email de cashback", "Permitir usar credito en futuras ofertas"],
    examples: ["Credito AFFILIX", "Cupon unico", "Fidelizacion"],
  },
  {
    id: "affilix-saas",
    level: "bronce",
    priority: false,
    title: "Vender AFFILIX como SaaS",
    potential: "$790-$3.950/mes adicionales",
    cost: "Dev 1 mes",
    time: "1 mes",
    summary: "Convertir AFFILIX en plataforma multi-cliente con planes de pago.",
    actions: ["Crear multi-tenancy", "Crear pagina de precios", "Aislar datos por cliente"],
    examples: ["Plan Pro", "Clientes propios", "Ingresos recurrentes"],
  },
  {
    id: "google-shopping",
    level: "bronce",
    priority: false,
    title: "Integracion Google Shopping",
    potential: "Trafico organico gratis",
    cost: "$0",
    time: "1 semana",
    summary: "Enviar feed de productos a Google Merchant Center para aparecer en Shopping.",
    actions: ["Crear Merchant Center", "Verificar dominio", "Generar feed de productos"],
    examples: ["merchant center", "feed XML", "trafico organico"],
  },
  {
    id: "mobile-pwa",
    level: "bronce",
    priority: false,
    title: "App movil PWA",
    potential: "3x engagement movil",
    cost: "$0",
    time: "1-2 dias",
    summary: "Convertir la tienda en app instalable desde movil con manifest y service worker.",
    actions: ["Anadir manifest", "Configurar PWA", "Optimizar iconos y cache"],
    examples: ["Instalar app", "Push futuro", "Experiencia movil"],
  },
  {
    id: "agency-whitelabel",
    level: "bronce",
    priority: false,
    title: "Whitelabel para agencias",
    potential: "$750-$3.000/mes",
    cost: "Dev 2 semanas",
    time: "2 semanas",
    summary: "Permitir que agencias usen AFFILIX con su marca, dominio y colores.",
    actions: ["Configurar marca blanca", "Permitir dominio propio", "Separar clientes por agencia"],
    examples: ["Logo agencia", "Dominio propio", "Panel personalizado"],
  },
  {
    id: "gaming-niche",
    level: "bronce",
    priority: false,
    title: "Nicho gaming",
    potential: "$80 por setup vendido",
    cost: "$0",
    time: "2 dias",
    summary: "Crear categoria gaming con Amazon, Twitch, YouTube y productos de alto ticket.",
    actions: ["Crear categoria Gaming", "Configurar keywords", "Publicar productos top de hardware"],
    examples: ["GPU", "monitor gaming", "raton gaming", "sillas gaming"],
  },
];
