import type { AutomationId, Platform } from "@/types";

export type PlatformSetup = {
  id: Platform;
  name: string;
  logo: string;
  commission: string;
  setupTime: string;
  category: "physical" | "digital" | "network" | "dropshipping";
  access: "free" | "paid" | "premium";
  tags: string[];
  signupUrl: string;
  requiredKeys: string[];
  description: string;
  steps: Array<{
    title: string;
    description: string;
    link?: string;
    tip?: string;
  }>;
};

export type SetupAutomation = {
  id: AutomationId;
  name: string;
  description: string;
  schedule: string;
  endpoint: string;
  result: string;
};

export const SETUP_PLATFORMS: PlatformSetup[] = [
  {
    id: "hotmart",
    name: "Hotmart",
    logo: "HM",
    commission: "Variable",
    setupTime: "20 min",
    category: "digital",
    access: "free",
    tags: ["Cursos", "Ebooks", "LatAm", "Digital"],
    signupUrl: "https://app.hotmart.com/",
    requiredKeys: ["Client ID", "Client Secret | Basic token"],
    description: "Cursos, ebooks, mentorias y productos digitales vendidos por Hotmart.",
    steps: [
      { title: "Crea o abre tu cuenta Hotmart", description: "Entra a Hotmart y activa tu perfil de productor o afiliado.", link: "https://app.hotmart.com/" },
      { title: "Crea credenciales Developers", description: "En Herramientas > Credenciales Developers copia Client ID, Client Secret y Basic token." },
      { title: "Importa por API o enlace", description: "La API valida tu cuenta; para productos afiliados aprobados puedes pegar el HotLink y AFFILIX extrae ficha/foto publica.", tip: "Hotmart no expone todo el marketplace afiliado como feed publico; AFFILIX no marca 100% sin credenciales reales." },
    ],
  },
  {
    id: "gumroad",
    name: "Gumroad",
    logo: "GR",
    commission: "Variable",
    setupTime: "15 min",
    category: "digital",
    access: "free",
    tags: ["Ebooks", "Plantillas", "Software", "Digital"],
    signupUrl: "https://gumroad.com/",
    requiredKeys: ["Access token"],
    description: "Productos digitales, plantillas, software, membresias y descargas directas.",
    steps: [
      { title: "Crea access token", description: "En Gumroad API genera un access token con permisos de productos.", link: "https://gumroad.com/api" },
      { title: "Guarda el token", description: "Pega el token como clave principal en AFFILIX." },
      { title: "Importa productos", description: "AFFILIX puede listar tus productos Gumroad y tambien importar enlaces individuales con foto publica." },
    ],
  },
  {
    id: "payhip",
    name: "Payhip",
    logo: "PH",
    commission: "Venta directa",
    setupTime: "15 min",
    category: "digital",
    access: "free",
    tags: ["Ebooks", "Licencias", "Descargas", "Digital"],
    signupUrl: "https://payhip.com/",
    requiredKeys: ["API key"],
    description: "Venta directa de ebooks, archivos digitales, cursos simples y licencias.",
    steps: [
      { title: "Crea API key", description: "En Payhip copia la API key disponible para su API publica.", link: "https://payhip.com/api-reference/introduction" },
      { title: "Guarda el acceso", description: "Pega la API key como clave principal." },
      { title: "Importa por enlace", description: "Payhip no ofrece feed completo de productos en su API publica actual; AFFILIX importa enlaces de producto con foto publica." },
    ],
  },
  {
    id: "warriorplus",
    name: "WarriorPlus",
    logo: "W+",
    commission: "Variable",
    setupTime: "20 min",
    category: "digital",
    access: "free",
    tags: ["Software", "Marketing", "Afiliados", "Digital"],
    signupUrl: "https://warriorplus.com/",
    requiredKeys: ["API key"],
    description: "Marketplace digital de ofertas, software y lanzamientos de marketing.",
    steps: [
      { title: "Crea API key", description: "En My Account > API Key copia tu clave.", link: "https://warriorplus.com/api/docs/" },
      { title: "Guarda la clave", description: "Pega la API key como clave principal." },
      { title: "Importa ofertas", description: "AFFILIX valida la API y permite importar enlaces reales aprobados por tu cuenta." },
    ],
  },
  {
    id: "systeme",
    name: "systeme.io",
    logo: "SIO",
    commission: "Venta directa",
    setupTime: "15 min",
    category: "digital",
    access: "free",
    tags: ["Funnels", "Cursos", "Email", "Digital"],
    signupUrl: "https://systeme.io/",
    requiredKeys: ["Public API key"],
    description: "Funnels, cursos, automatizaciones y productos digitales vendidos desde systeme.io.",
    steps: [
      { title: "Crea Public API key", description: "En Settings > Public API keys crea y copia el token.", link: "https://help.systeme.io/article/2323-how-to-create-a-public-api-key-on-systeme-io" },
      { title: "Guarda el token", description: "Pega el token como clave principal." },
      { title: "Importa por enlace", description: "AFFILIX puede publicar productos desde tus enlaces de funnel/producto y cargar foto publica si existe." },
    ],
  },
  {
    id: "clickbank",
    name: "ClickBank",
    logo: "CB",
    commission: "30% - 75%",
    setupTime: "20 min",
    category: "digital",
    access: "free",
    tags: ["Gratis", "Digital", "Alta comision"],
    signupUrl: "https://accounts.clickbank.com/signup/",
    requiredKeys: ["API key", "Nickname"],
    description: "Productos digitales con comisiones altas y pagos frecuentes.",
    steps: [
      { title: "Crea la cuenta", description: "Abre ClickBank, completa el perfil fiscal y activa Marketplace como afiliado.", link: "https://accounts.clickbank.com/signup/" },
      { title: "Copia API key y nickname", description: "En Account Settings genera la API key y guarda el nickname exacto de afiliado." },
      { title: "Pega credenciales en AFFILIX", description: "Guarda API key como clave principal y nickname como clave secundaria.", tip: "El agente filtra por gravity mayor de 20 y comision alta." },
    ],
  },
  {
    id: "amazon",
    name: "Amazon Associates",
    logo: "A",
    commission: "3% - 10%",
    setupTime: "30 min",
    category: "physical",
    access: "free",
    tags: ["Gratis", "Fisicos"],
    signupUrl: "https://affiliate-program.amazon.com",
    requiredKeys: ["Access key", "Secret key", "Associate tag"],
    description: "Catalogo masivo de productos fisicos con tracking por Associate Tag.",
    steps: [
      { title: "Crea tu cuenta de afiliado", description: "Registra tu web o perfil social en Amazon Associates.", link: "https://affiliate-program.amazon.com" },
      { title: "ObtÃ©n el Associate Tag", description: "Copia el Store ID o tag que aparece despues de ?tag= en tus enlaces." },
      { title: "Activa Product Advertising API", description: "Crea Access Key y Secret Key en Product Advertising API.", link: "https://affiliate-program.amazon.com/assoc_credentials/home", tip: "La API requiere ventas calificadas para permanecer activa." },
    ],
  },
  {
    id: "amazon_seller",
    name: "Amazon Seller Central",
    logo: "AS",
    commission: "Venta directa",
    setupTime: "45 min",
    category: "physical",
    access: "premium",
    tags: ["Vendedor", "SP-API", "Publicacion"],
    signupUrl: "https://sellercentral.amazon.com/",
    requiredKeys: ["Seller ID", "Marketplace ID", "LWA Client ID", "LWA Client Secret", "Refresh token"],
    description: "Cuenta de vendedor para publicar productos en Amazon mediante Seller Central y SP-API.",
    steps: [
      { title: "Entra a Seller Central", description: "Abre tu cuenta de vendedor o completa el registro oficial.", link: "https://sellercentral.amazon.com/" },
      { title: "Autoriza la aplicacion SP-API", description: "Amazon debe autorizar el acceso con Login with Amazon para generar refresh token." },
      { title: "Guarda credenciales en AFFILIX", description: "Pega Seller ID, Marketplace ID, LWA Client ID, LWA Client Secret y refresh token para activar publicacion automatica.", tip: "Sin autorizacion SP-API real, AFFILIX no debe fingir publicaciones en Amazon." },
    ],
  },
  {
    id: "ebay",
    name: "eBay Partner Network",
    logo: "eB",
    commission: "1% - 4%",
    setupTime: "25 min",
    category: "physical",
    access: "free",
    tags: ["Gratis", "Fisicos"],
    signupUrl: "https://partnernetwork.ebay.com/",
    requiredKeys: ["Campaign ID", "Client ID", "Client secret"],
    description: "Productos fisicos, subastas y ofertas con programa global.",
    steps: [
      { title: "Registra la cuenta", description: "Crea tu cuenta en eBay Partner Network y completa datos de pago.", link: "https://partnernetwork.ebay.com/" },
      { title: "Crea campaign ID", description: "Genera una campaign para rastrear clics y ventas desde AFFILIX." },
      { title: "Configura API", description: "Copia Client ID y Client Secret desde el developer portal de eBay." },
    ],
  },
  {
    id: "rakuten",
    name: "Rakuten Advertising",
    logo: "R",
    commission: "Variable",
    setupTime: "35 min",
    category: "network",
    access: "premium",
    tags: ["Marcas", "Red"],
    signupUrl: "https://rakutenadvertising.com/",
    requiredKeys: ["API token", "Publisher ID"],
    description: "Red de anunciantes para marcas grandes y campaÃ±as por publisher.",
    steps: [
      { title: "Solicita publisher account", description: "Registra tu propiedad y espera aprobacion de Rakuten.", link: "https://rakutenadvertising.com/" },
      { title: "Conecta anunciantes", description: "Aplica a programas compatibles con tus nichos." },
      { title: "Guarda API token", description: "Pega Publisher ID y token para importar ofertas aprobadas." },
    ],
  },
  {
    id: "digistore",
    name: "Digistore24",
    logo: "D24",
    commission: "20% - 70%",
    setupTime: "20 min",
    category: "digital",
    access: "free",
    tags: ["Gratis", "Digital"],
    signupUrl: "https://www.digistore24.com/",
    requiredKeys: ["API key", "Affiliate ID opcional"],
    description: "Marketplace digital europeo con productos de alta comision.",
    steps: [
      { title: "Crea cuenta", description: "Abre Digistore24 y activa el rol de afiliado.", link: "https://www.digistore24.com/" },
      { title: "Busca productos aprobados", description: "Elige ofertas con buena conversion y comision." },
      { title: "Guarda API key", description: "Pega API key y Affiliate ID en AFFILIX para sincronizar productos." },
    ],
  },
  {
    id: "jvzoo",
    name: "JVZoo",
    logo: "JV",
    commission: "30% - 75%",
    setupTime: "25 min",
    category: "digital",
    access: "free",
    tags: ["Digital", "Software"],
    signupUrl: "https://www.jvzoo.com/",
    requiredKeys: ["API key", "Affiliate ID"],
    description: "Software, cursos y lanzamientos digitales con pago por afiliado.",
    steps: [
      { title: "Abre cuenta JVZoo", description: "Completa perfil y datos de pago.", link: "https://www.jvzoo.com/" },
      { title: "Solicita aprobacion", description: "Pide acceso a vendedores relevantes para tu nicho." },
      { title: "Conecta credenciales", description: "Guarda API key como clave principal. JVZoo valida con Basic Auth usando API_KEY:x; el Affiliate ID solo ayuda a organizar enlaces aprobados." },
    ],
  },
  {
    id: "cj",
    name: "CJ Affiliate",
    logo: "CJ",
    commission: "Variable",
    setupTime: "40 min",
    category: "network",
    access: "premium",
    tags: ["Marcas", "Red"],
    signupUrl: "https://www.cj.com/",
    requiredKeys: ["Personal access token", "Website ID"],
    description: "Red de afiliados con marcas grandes y productos fisicos/digitales.",
    steps: [
      { title: "Crea publisher account", description: "Registra sitio, categoria y datos de pago en CJ.", link: "https://www.cj.com/" },
      { title: "Aplica a anunciantes", description: "Solicita entrada a programas alineados con tus nichos." },
      { title: "Copia token y Website ID", description: "Guarda ambos datos para consultar productos y comisiones." },
    ],
  },
  {
    id: "shareasale",
    name: "ShareASale",
    logo: "SA",
    commission: "5% - 30%",
    setupTime: "30 min",
    category: "network",
    access: "premium",
    tags: ["Gratis", "Marcas"],
    signupUrl: "https://www.shareasale.com/",
    requiredKeys: ["Token", "Affiliate ID"],
    description: "Miles de marcas para afiliados con feed de productos.",
    steps: [
      { title: "Registra tu cuenta", description: "Crea cuenta de afiliado y valida tu propiedad.", link: "https://www.shareasale.com/" },
      { title: "Unete a merchants", description: "Aplica a marcas de tus nichos principales." },
      { title: "Guarda token", description: "Pega token y Affiliate ID para importar feeds de productos." },
    ],
  },
  {
    id: "impact",
    name: "Impact",
    logo: "IM",
    commission: "Variable",
    setupTime: "35 min",
    category: "network",
    access: "premium",
    tags: ["Marcas", "Red"],
    signupUrl: "https://impact.com/",
    requiredKeys: ["Account SID", "Auth token"],
    description: "Partnership automation para marcas y campaÃ±as con API estable.",
    steps: [
      { title: "Crea partner account", description: "Registra tus canales y completa aprobacion.", link: "https://impact.com/" },
      { title: "Aplica a marcas", description: "Elige campaÃ±as por nicho y condiciones de comision." },
      { title: "Copia credenciales API", description: "Guarda Account SID y Auth Token para sincronizacion." },
    ],
  },
  {
    id: "awin",
    name: "Awin",
    logo: "AW",
    commission: "Variable",
    setupTime: "35 min",
    category: "network",
    access: "premium",
    tags: ["Marcas", "Red"],
    signupUrl: "https://www.awin.com/",
    requiredKeys: ["API token", "Publisher ID"],
    description: "Red global de afiliados con productos fisicos y servicios.",
    steps: [
      { title: "Abre publisher account", description: "Registra tu medio y completa verificacion.", link: "https://www.awin.com/" },
      { title: "Conecta programas", description: "Aplica a anunciantes aprobados para tus nichos." },
      { title: "Guarda API token", description: "Pega token y Publisher ID para importar ofertas." },
    ],
  },
  {
    id: "spocket",
    name: "Spocket",
    logo: "SP",
    commission: "Margen propio",
    setupTime: "30 min",
    category: "dropshipping",
    access: "paid",
    tags: ["Dropshipping", "Fisicos"],
    signupUrl: "https://www.spocket.co/",
    requiredKeys: ["API key", "Store ID"],
    description: "Dropshipping con proveedores USA/EU y margen definido por tu tienda.",
    steps: [
      { title: "Crea cuenta Spocket", description: "Abre cuenta y configura datos de tienda.", link: "https://www.spocket.co/" },
      { title: "Selecciona proveedores", description: "Elige productos con buen envio y margen viable." },
      { title: "Conecta API", description: "Guarda API key y Store ID para importar catalogo." },
    ],
  },
  {
    id: "cjdrop",
    name: "CJ Dropshipping",
    logo: "CD",
    commission: "Margen propio",
    setupTime: "25 min",
    category: "dropshipping",
    access: "free",
    tags: ["Gratis", "Dropshipping"],
    signupUrl: "https://cjdropshipping.com/",
    requiredKeys: ["Email", "API key"],
    description: "Dropshipping con almacenes internacionales y automatizacion de catalogo.",
    steps: [
      { title: "Crea cuenta gratis", description: "Registra CJ Dropshipping y completa datos de negocio.", link: "https://cjdropshipping.com/" },
      { title: "Solicita API key", description: "En Account > API solicita o copia tu API key." },
      { title: "Guarda credenciales", description: "Pega email y API key; el agente importara productos con fotos y precios." },
    ],
  },
  {
    id: "walmart",
    name: "Walmart Affiliates",
    logo: "WM",
    commission: "1% - 4%",
    setupTime: "25 min",
    category: "physical",
    access: "free",
    tags: ["Gratis", "Fisicos", "Retail"],
    signupUrl: "https://affiliates.walmart.com/",
    requiredKeys: ["Publisher ID", "API key"],
    description: "Programa de afiliados de Walmart para hogar, electronica, alimentacion y retail USA.",
    steps: [
      { title: "Solicita cuenta", description: "Entra a affiliates.walmart.com y completa la aplicacion con tu web o canal.", link: "https://affiliates.walmart.com/" },
      { title: "Espera aprobacion", description: "La aprobacion suele tardar varios dias habiles." },
      { title: "Guarda credenciales", description: "Pega Publisher ID y API key si tu cuenta aprobada las ofrece." },
    ],
  },
  {
    id: "etsy",
    name: "Etsy Affiliate Program",
    logo: "ET",
    commission: "4% - 8%",
    setupTime: "25 min",
    category: "physical",
    access: "premium",
    tags: ["Gratis", "Awin", "Artesanal"],
    signupUrl: "https://www.etsy.com/affiliates",
    requiredKeys: ["Awin Publisher ID", "Tracking ID"],
    description: "Productos handmade, vintage y personalizados. Se gestiona mediante Awin.",
    steps: [
      { title: "Abre Etsy Affiliates", description: "Solicita acceso al programa oficial desde Etsy.", link: "https://www.etsy.com/affiliates" },
      { title: "Conecta Awin", description: "El programa se gestiona a traves de Awin; necesitas aprobacion." },
      { title: "Guarda IDs", description: "Pega Publisher ID y Tracking ID para organizar enlaces." },
    ],
  },
  {
    id: "temu",
    name: "Temu Affiliate",
    logo: "TM",
    commission: "5% - 20%",
    setupTime: "15 min",
    category: "physical",
    access: "free",
    tags: ["Gratis", "Fisicos", "TikTok"],
    signupUrl: "https://www.temu.com/affiliate.html",
    requiredKeys: ["Affiliate ID", "Tracking code"],
    description: "Marketplace de productos economicos con comisiones y bonos por nuevos usuarios.",
    steps: [
      { title: "Crea cuenta", description: "Entra al programa afiliado de Temu y registrate.", link: "https://www.temu.com/affiliate.html" },
      { title: "Copia tu ID", description: "Guarda Affiliate ID o codigo de tracking generado por Temu." },
      { title: "Publica por enlace", description: "Pega enlaces reales aprobados para cargar foto publica cuando sea posible." },
    ],
  },
  {
    id: "shein",
    name: "SHEIN Affiliate Program",
    logo: "SH",
    commission: "10% - 20%",
    setupTime: "20 min",
    category: "physical",
    access: "free",
    tags: ["Gratis", "Moda", "Fisicos"],
    signupUrl: "https://www.sheincorp.com/affiliate",
    requiredKeys: ["Affiliate ID", "Tracking code"],
    description: "Programa de moda con cookie larga y alto volumen en redes sociales.",
    steps: [
      { title: "Solicita acceso", description: "Entra a SHEIN Affiliate y registra tu canal.", link: "https://www.sheincorp.com/affiliate" },
      { title: "Copia tracking", description: "Guarda tu Affiliate ID o tracking code." },
      { title: "Publica enlaces", description: "Usa enlaces oficiales de SHEIN para publicar productos." },
    ],
  },
  {
    id: "flexoffers",
    name: "FlexOffers",
    logo: "FX",
    commission: "Variable",
    setupTime: "30 min",
    category: "network",
    access: "premium",
    tags: ["Gratis", "Red", "Marcas"],
    signupUrl: "https://www.flexoffers.com/",
    requiredKeys: ["API key", "Publisher ID"],
    description: "Red de afiliados con miles de anunciantes y ofertas por categoria.",
    steps: [
      { title: "Registra publisher", description: "Crea tu cuenta en FlexOffers y completa aprobacion.", link: "https://www.flexoffers.com/" },
      { title: "Aplica a anunciantes", description: "Selecciona programas compatibles con tus nichos." },
      { title: "Guarda API", description: "Pega API key y Publisher ID si tu cuenta tiene acceso API." },
    ],
  },
  {
    id: "partnerstack",
    name: "PartnerStack",
    logo: "PS",
    commission: "15% - 50% rec",
    setupTime: "25 min",
    category: "network",
    access: "free",
    tags: ["Gratis", "SaaS", "Recurrente"],
    signupUrl: "https://partnerstack.com/",
    requiredKeys: ["Partner ID", "API key"],
    description: "Marketplace de programas SaaS con comisiones recurrentes mensuales.",
    steps: [
      { title: "Crea cuenta partner", description: "Entra a PartnerStack y registrate como partner.", link: "https://partnerstack.com/" },
      { title: "Elige programas", description: "Aplica a los programas SaaS que encajen con tu nicho." },
      { title: "Guarda datos", description: "Pega Partner ID y API key si el programa lo permite." },
    ],
  },
  {
    id: "fiverr",
    name: "Fiverr Affiliates",
    logo: "FV",
    commission: "$15 - $150",
    setupTime: "20 min",
    category: "network",
    access: "free",
    tags: ["Gratis", "SaaS", "Servicios"],
    signupUrl: "https://affiliates.fiverr.com/",
    requiredKeys: ["Affiliate ID", "Tracking ID"],
    description: "Programa del marketplace de freelancers con CPA fijo y revenue share.",
    steps: [
      { title: "Registrate", description: "Crea cuenta en Fiverr Affiliates.", link: "https://affiliates.fiverr.com/" },
      { title: "Elige plan", description: "Selecciona CPA o hybrid segun tu estrategia." },
      { title: "Guarda tracking", description: "Pega Affiliate ID y Tracking ID." },
    ],
  },
  {
    id: "shopify",
    name: "Shopify Affiliates",
    logo: "SF",
    commission: "20% rec",
    setupTime: "25 min",
    category: "network",
    access: "premium",
    tags: ["Gratis", "SaaS", "Ecommerce"],
    signupUrl: "https://www.shopify.com/affiliates",
    requiredKeys: ["Partner ID", "Tracking link"],
    description: "Programa de afiliados de Shopify para recomendar la plataforma ecommerce.",
    steps: [
      { title: "Solicita acceso", description: "Aplica al programa afiliado de Shopify.", link: "https://www.shopify.com/affiliates" },
      { title: "Espera aprobacion", description: "Shopify revisa tu canal antes de aprobar." },
      { title: "Guarda tracking", description: "Pega Partner ID o enlace de tracking oficial." },
    ],
  },
  {
    id: "semrush",
    name: "Semrush Affiliates",
    logo: "SE",
    commission: "$200/venta",
    setupTime: "25 min",
    category: "network",
    access: "premium",
    tags: ["Gratis", "SaaS", "SEO"],
    signupUrl: "https://www.semrush.com/affiliates/",
    requiredKeys: ["Impact Account SID", "Tracking link"],
    description: "Programa premium de herramienta SEO con comision alta por suscripcion.",
    steps: [
      { title: "Aplica al programa", description: "Entra a Semrush Affiliates y solicita acceso.", link: "https://www.semrush.com/affiliates/" },
      { title: "Gestiona via red", description: "Semrush puede gestionarse mediante red afiliada como Impact." },
      { title: "Guarda tracking", description: "Pega datos de Impact o tracking link aprobado." },
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot Affiliates",
    logo: "HB",
    commission: "30% rec",
    setupTime: "25 min",
    category: "network",
    access: "premium",
    tags: ["Gratis", "SaaS", "CRM"],
    signupUrl: "https://www.hubspot.com/partners/affiliates",
    requiredKeys: ["Affiliate ID", "Tracking link"],
    description: "Programa SaaS/CRM con comisiones recurrentes para planes HubSpot.",
    steps: [
      { title: "Solicita acceso", description: "Aplica desde la pagina oficial de afiliados.", link: "https://www.hubspot.com/partners/affiliates" },
      { title: "Espera aprobacion", description: "HubSpot revisa tu canal y estrategia." },
      { title: "Guarda tracking", description: "Pega Affiliate ID o enlace oficial." },
    ],
  },
  {
    id: "booking",
    name: "Booking.com Affiliate",
    logo: "BK",
    commission: "25% - 40%",
    setupTime: "20 min",
    category: "network",
    access: "free",
    tags: ["Gratis", "Viajes", "Hoteles"],
    signupUrl: "https://www.booking.com/affiliate-program/",
    requiredKeys: ["Affiliate ID", "Tracking link"],
    description: "Programa de hoteles y viajes con comision sobre reservas.",
    steps: [
      { title: "Crea cuenta", description: "Registrate en Booking Affiliate Partner Program.", link: "https://www.booking.com/affiliate-program/" },
      { title: "Genera enlaces", description: "Crea enlaces oficiales de alojamiento o destino." },
      { title: "Guarda tracking", description: "Pega Affiliate ID o tracking link." },
    ],
  },
  {
    id: "agoda",
    name: "Agoda Affiliate Program",
    logo: "AG",
    commission: "Hasta 7%",
    setupTime: "20 min",
    category: "network",
    access: "free",
    tags: ["Gratis", "Viajes", "Hoteles"],
    signupUrl: "https://www.agoda.com/affiliates",
    requiredKeys: ["Affiliate ID", "API key"],
    description: "Programa de hoteles y viajes con inventario internacional.",
    steps: [
      { title: "Registrate", description: "Abre cuenta en Agoda Affiliates.", link: "https://www.agoda.com/affiliates" },
      { title: "Activa herramientas", description: "Solicita herramientas/API si tu cuenta las permite." },
      { title: "Guarda datos", description: "Pega Affiliate ID y API key si esta disponible." },
    ],
  },
  {
    id: "coinbase",
    name: "Coinbase Affiliate",
    logo: "CB",
    commission: "$10/user",
    setupTime: "20 min",
    category: "network",
    access: "premium",
    tags: ["Gratis", "Crypto", "Finanzas"],
    signupUrl: "https://www.coinbase.com/affiliates",
    requiredKeys: ["Affiliate ID", "Tracking link"],
    description: "Programa crypto con pago por usuario referido que compra.",
    steps: [
      { title: "Aplica al programa", description: "Solicita acceso desde Coinbase Affiliates.", link: "https://www.coinbase.com/affiliates" },
      { title: "Espera aprobacion", description: "Coinbase revisa perfil y cumplimiento." },
      { title: "Guarda tracking", description: "Pega Affiliate ID o enlace oficial." },
    ],
  },
  {
    id: "binance",
    name: "Binance Affiliate",
    logo: "BN",
    commission: "Hasta 40%",
    setupTime: "20 min",
    category: "network",
    access: "premium",
    tags: ["Gratis", "Crypto", "Finanzas"],
    signupUrl: "https://www.binance.com/activity/affiliate",
    requiredKeys: ["Referral ID", "Tracking link"],
    description: "Programa crypto con comisiones por actividad de usuarios referidos.",
    steps: [
      { title: "Solicita afiliado", description: "Aplica al programa oficial de Binance.", link: "https://www.binance.com/activity/affiliate" },
      { title: "Cumple requisitos", description: "Binance puede exigir volumen, audiencia o aprobacion." },
      { title: "Guarda tracking", description: "Pega Referral ID o enlace oficial." },
    ],
  },
  {
    id: "aliexpress",
    name: "AliExpress Portals",
    logo: "AX",
    commission: "3% - 9%",
    setupTime: "20 min",
    category: "physical",
    access: "free",
    tags: ["Gratis", "Fisicos", "Marketplace"],
    signupUrl: "https://portals.aliexpress.com/",
    requiredKeys: ["App key", "Tracking ID"],
    description: "Marketplace global de productos economicos con programa afiliado AliExpress Portals.",
    steps: [
      { title: "Registrate", description: "Crea cuenta en AliExpress Portals.", link: "https://portals.aliexpress.com/" },
      { title: "Genera tracking", description: "Crea tus enlaces o tracking ID." },
      { title: "Guarda datos", description: "Pega App key y Tracking ID si estan disponibles." },
    ],
  },
  {
    id: "teachable",
    name: "Teachable Affiliate",
    logo: "TC",
    commission: "30% rec",
    setupTime: "20 min",
    category: "digital",
    access: "free",
    tags: ["Gratis", "Cursos", "Digital"],
    signupUrl: "https://teachable.com/affiliates",
    requiredKeys: ["Affiliate ID", "Tracking link"],
    description: "Programa para promocionar Teachable y cursos digitales con comision recurrente.",
    steps: [
      { title: "Aplica al programa", description: "Registrate en Teachable Affiliates.", link: "https://teachable.com/affiliates" },
      { title: "Genera enlaces", description: "Copia tus enlaces oficiales aprobados." },
      { title: "Guarda tracking", description: "Pega Affiliate ID o tracking link." },
    ],
  },
];

export const SETUP_AUTOMATIONS: SetupAutomation[] = [
  { id: "auto_discover", name: "Descubrimiento de productos", description: "Busca productos nuevos en todas las plataformas conectadas.", schedule: "0 9 * * *", endpoint: "/api/automation/cron-discover", result: "Agrega 5-20 productos por dia segun filtros." },
  { id: "auto_content", name: "Generacion de contenido IA", description: "Genera descripcion, review, SEO title y meta descripcion.", schedule: "0 2 * * *", endpoint: "/api/automation/cron-content", result: "Productos publicados con contenido optimizado." },
  { id: "auto_prices", name: "Actualizacion de precios", description: "Verifica precios y disponibilidad en proveedores.", schedule: "0 */6 * * *", endpoint: "/api/automation/cron-prices", result: "Precios actualizados cada 6 horas." },
  { id: "auto_new_releases", name: "Nuevos lanzamientos", description: "Importa lanzamientos recientes de catalogos compatibles.", schedule: "0 * * * *", endpoint: "/api/automation/cron-new-releases", result: "Primero en tu nicho con productos nuevos." },
  { id: "auto_commissions", name: "Alertas de comisiones", description: "Registra y notifica nuevas comisiones desde webhooks.", schedule: "Tiempo real", endpoint: "/api/analytics/commission", result: "Avisos cuando entra una venta." },
  { id: "auto_master_agent", name: "Agente IA Maestro", description: "Ejecuta el ciclo completo y prioriza productos por rendimiento.", schedule: "0 3 * * *", endpoint: "/api/ai/agent", result: "Sistema optimizado por datos." },
];

export const SETUP_CHECKLIST = [
  "Deploy del sistema AFFILIX en Vercel",
  "Configurar API de IA en Settings > Config IA",
  "Crear cuenta en ClickBank y pegar Nickname + API Key",
  "Crear cuenta en Amazon Associates y pegar Tag + API Keys",
  "Conectar ShareASale o CJ para marcas grandes",
  "Configurar 3-5 nichos con filtros de precio, rating y plataforma",
  "Activar el switch maestro de automatizacion",
  "Ejecutar el primer ciclo manual del Agente IA",
  "Revisar productos importados antes de enviar trafico",
  "Conectar dropshipping si quieres margen propio",
];

